### ISSUE TITLE
Diarization is taking 90+ minutes, is that normal? 

### ISSUE THREAD

**Issue by josh-may** [lablab-ai/Whisper-transcription_and_diarization-speaker-identification-#1]
I'm went through the repo and I go to this part:

```
DEMO_FILE = {'uri': 'blabal', 'audio': 'audio.wav'}
dz = pipeline(DEMO_FILE)  

with open("diarization.txt", "w") as text_file:
    text_file.write(str(dz))
```

But it's now been running for 65+ minutes. And this is for the 20 min audio file mentioned in the repo. 

![Screenshot at Dec 09 05-54-08](https://user-images.githubusercontent.com/72312238/206700781-2ccc1a7a-a5e1-4222-a274-ca064f478441.png)

How long should the diarization take?

**Comment by andytyrer** [comment]
Hi, yes having the same problem. It's at 1hr 4mins on the runtime for a 20 min file

**Comment by EngineNeo** [comment]
I was able to finish the Diarization in 3 minutes using Google Collab with GPU execution for a 55 minute audio file

**Comment by dbtreasure** [comment]
I plugged into a M60 nvidia on azure ML workspaces through VS code and was able to still utilize github copilot and stay in my IDE and it finished an hour episode of a podcast in 10m

**Comment by ezzcodeezzlife** [comment]
like most people here said, it depends on the length of the audio file, your hardware and on the size of the Whisper model you choose.

**Comment by patrickwangym** [comment]
I have RTX 3060, after downloading and installing CUDA, it finished the processing in around 17 minutes. Before that, it took forever and I gave up in the end. 
If you have a CUDA-capable GPU, you can follow the guide below to install the CUDA version of PyTorch. It does make a lot of difference. 
https://pytorch.org/get-started/locally/
