### ISSUE TITLE
Output to a text file and modifications for an aribtrary number of speakers

### ISSUE THREAD

**Issue by skye-repos** [lablab-ai/Whisper-transcription_and_diarization-speaker-identification-#5]
Hi!

I love this. This is exactly what i've been looking for.

Could you guide me on how to modify this so the the output file is a txt file and to account for arbitrary number of speakers? Its ok for me if the speakers don't get named. Speaker 1, 2, 3 etc is enough.

Best,
KSH

**Comment by ezzcodeezzlife** [comment]
related to https://github.com/lablab-ai/Whisper-transcription_and_diarization-speaker-identification-/issues/3 lets keep this in one issue if someone has a solution for this
