### ISSUE TITLE
Fix for library dependency issue

### ISSUE THREAD

**Issue by anEEStudent** [lablab-ai/Whisper-transcription_and_diarization-speaker-identification-#6]
Hi all, 
I have managed to fix the library dependency issue by installing 
`huggingface-hub version 0.15.1` and changing this line in `C:\Users\<UserName>\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyannote\audio\core\model.py` from `from pytorch_lightning.utilities.cloud_io import load as pl_load` to `from lightning_fabric.utilities.cloud_io import _load as pl_load`

**Comment by ezzcodeezzlife** [comment]
THank you for the information 🚀
